
CREATE TYPE public.app_role AS ENUM ('admin', 'user');

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  email text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE POLICY "Signed in users can view roles" ON public.user_roles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage roles" ON public.user_roles
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.donations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_no bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  donor_name text NOT NULL,
  donor_phone text,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  lane text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid')),
  upi_ref text,
  note text,
  collected_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  collected_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  paid_at timestamptz
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.donations TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON public.donations TO service_role;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Signed in users can view donations" ON public.donations
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Signed in users can record donations" ON public.donations
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = collected_by);
CREATE POLICY "Owner or admin can update donations" ON public.donations
  FOR UPDATE TO authenticated
  USING (auth.uid() = collected_by OR public.has_role(auth.uid(), 'admin'))
  WITH CHECK (auth.uid() = collected_by OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete donations" ON public.donations
  FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

CREATE INDEX donations_created_at_idx ON public.donations (created_at DESC);
CREATE INDEX donations_lane_idx ON public.donations (lane);

CREATE TABLE public.receipt_settings (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  mandal_name text NOT NULL DEFAULT 'Shantinagar Sarvajanik Mitra Mandal',
  address text NOT NULL DEFAULT '',
  contact text NOT NULL DEFAULT '',
  upi_id text NOT NULL DEFAULT '',
  header_text text NOT NULL DEFAULT '|| Shree Ganeshay Namah ||',
  footer_text text NOT NULL DEFAULT 'Ganpati Bappa Morya!',
  logo_url text,
  paper_width text NOT NULL DEFAULT '58mm' CHECK (paper_width IN ('58mm','80mm')),
  show_phone boolean NOT NULL DEFAULT true,
  show_lane boolean NOT NULL DEFAULT true,
  show_collector boolean NOT NULL DEFAULT true,
  show_upi_ref boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.receipt_settings TO authenticated;
GRANT ALL ON public.receipt_settings TO service_role;
ALTER TABLE public.receipt_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Signed in users can view receipt settings" ON public.receipt_settings
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage receipt settings" ON public.receipt_settings
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

INSERT INTO public.receipt_settings (id, mandal_name, address, contact, upi_id)
VALUES (true, 'Shantinagar Sarvajanik Mitra Mandal', 'Shantinagar, Pune', '', 'adityapawar8552@okaxis');

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''), NEW.email)
  ON CONFLICT (id) DO NOTHING;

  IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'admin') THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin');
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'user')
    ON CONFLICT DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
